name: Build

on:
  push:
    branches: 
        - "*"
  pull_request:


jobs:
  format:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'
    
        - name: Install dependencies
          run: |
            pip install pipenv
            pipenv install --dev
    
        - name: Verify format
          run: pipenv run fmt