name: Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      NEXT_RELEASE: ${{ env.NEXT_RELEASE }}
      VERSION: ${{ env.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        #with:
        #  token: ${{ secrets.GH_TOKEN }}
  
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
  
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
 
      - name: Get version
        run: echo "::set-output name=project_version::$(grep 'VERSION =' config/config.py | cut -d'"' -f2)"

      - name: Display Version
        run: echo "project Version ${{ env.PROJECT_VERSION }}"